# Generated by Django 3.1 on 2020-11-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('cid', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('oper_init', models.CharField(max_length=16)),
                ('home_facility', models.CharField(blank=True, max_length=32, null=True)),
                ('rating', models.CharField(max_length=32)),
                ('main_role', models.CharField(max_length=32)),
                ('staff_role', models.CharField(blank=True, max_length=32, null=True)),
                ('training_role', models.CharField(blank=True, max_length=32, null=True)),
                ('mentor_level', models.CharField(blank=True, max_length=32, null=True)),
                ('del_cert', models.IntegerField(choices=[(0, 'No Endorsement'), (1, 'Minor Endorsement'), (2, 'Major Endorsement'), (3, 'Solo Endorsement')], default=0)),
                ('gnd_cert', models.IntegerField(choices=[(0, 'No Endorsement'), (1, 'Minor Endorsement'), (2, 'Major Endorsement'), (3, 'Solo Endorsement')], default=0)),
                ('twr_cert', models.IntegerField(choices=[(0, 'No Endorsement'), (1, 'Minor Endorsement'), (2, 'Major Endorsement'), (3, 'Solo Endorsement')], default=0)),
                ('app_cert', models.IntegerField(choices=[(0, 'No Endorsement'), (1, 'Minor Endorsement'), (2, 'Major Endorsement'), (3, 'Solo Endorsement')], default=0)),
                ('ctr_cert', models.IntegerField(choices=[(0, 'No Endorsement'), (1, 'Minor Endorsement'), (2, 'Major Endorsement'), (3, 'Solo Endorsement')], default=0)),
                ('solo_cert', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('staff_comment', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'LOA'), (2, 'Inactive')], default=0)),
                ('loa_until', models.DateField(blank=True, null=True)),
                ('loa_last_month', models.BooleanField(default=False)),
                ('activity_exempt', models.BooleanField(default=False)),
                ('prevent_event_signup', models.BooleanField(default=False)),
                ('staff_comment_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
