version: "3.8"

services:
  zid_postgres:
    platform: linux/amd64
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_CREDS_PSW}
      POSTGRES_USER: ${POSTGRES_CREDS_USR}
      POSTGRES_DB: ${POSTGRES_DB}

  zid_django:
    platform: linux/amd64
    image: zid_web:${BUILD_VERSION}
    command: /app/docker/start.sh
    volumes:
      - .:/code
    depends_on:
      - zid_postgres
    ports:
      - "8082:8000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_CREDS_PSW}
      POSTGRES_USER: ${POSTGRES_CREDS_USR}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}