# Generated by Django 3.1 on 2020-11-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_visitrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=16)),
                ('service_level', models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Fair'), (4, 'Needs Improvement'), (5, 'Unsatisfactory/Poor')])),
                ('flight_callsign', models.CharField(max_length=16)),
                ('pilot_name', models.CharField(blank=True, max_length=64, null=True)),
                ('pilot_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('pilot_cid', models.IntegerField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Posted'), (2, 'Rejected')], default=0)),
                ('staff_comment', models.TextField(blank=True, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
