name: Release App

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Release App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Next Version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: calver

      - name: Create New Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.v-version }}
          tag_exists_error: false

      - name: Create New Version
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.v-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            name=zidwm/zid-web
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.v-version }}

      - name: Log In to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}