name: Build App

on:
  pull_request:

jobs:
  check_deploy:
    name: Check Django deployment settings
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: prod
      SECRET_KEY: abc123
      WEBSITE_DOMAIN: zidartcc.org

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Check Django Security Settings
        run: |
          python manage.py check --deploy

  pylint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs:
      - check_deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run PyLint
        run: |
          pylint apps/ --fail-under=1

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs:
      - check_deploy
      - pylint

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log In to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Tag Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: zidwm/zid-web:PR-${{ github.event.number }}
