name: Move Trello Card for Pull Request Closed
run-name: ${{ github.workflow }}

on:
  pull_request:
    types: closed
    branches:
      - master

jobs:
  move_card_when_pull_request_closed:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    steps:
      - name: Call trello-github-actions
        id: call-trello-github-actions
        uses: jessicazu/trello-github-actions@v1.0
        with:
          trello-action: move_card_when_pull_request_closed
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_DEPARTURE_LIST_ID: ${{ secrets.TRELLO_REVIEW_LIST_ID }}
          TRELLO_DESTINATION_LIST_ID: ${{ secrets.TRELLO_READY_LIST_ID }}
